name: example
description: An example implementation for a SlidingSheet.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  charts_flutter: any
  flutter:
    sdk: flutter
  sliding_sheet:
    path: ../
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
   - assets/maps_screenshot.png